### ISSUE TITLE
Issue with Training

### ISSUE THREAD

**Issue by wtegge2** [AISE-TUDelft/Capybara-BinT5#8]
I ran into an issue while trying to train the model. I run the command below to start the training:
python3 run_exp.py --model_tag codet5_base --task summarize --sub_task C |& tee log.txt

The code throws an Assertion Error at line 162 in run_exp.py (images included). Upon inspection, I see that it calls the get_sub_tasks function in the same file, and it gets the sub_tasks based on the argument passed in. Since I am passing in "summarize", it gets the sub_tasks list below:
sub_tasks = ['ruby', 'javascript', 'go', 'python', 'java', 'php']

I am confused because the setup instructions do not specify to create folders for training with these languages. The languages included in the setup are C, decomC, demiStripped, and strippedDecomC. I am unsure if this was done intentionally or not. Can you provide a solution to this error and let me know if this code is correct or not, please? 

![assertion_error](https://github.com/AISE-TUDelft/Capybara-BinT5/assets/80014792/ca3a3fa6-e473-4cb7-8f54-85218fcb2cad)
![assertion_error_in_code](https://github.com/AISE-TUDelft/Capybara-BinT5/assets/80014792/562d1cd0-7748-4904-9c3e-7258b6969094)

**Comment by aalkaswan** [comment]
Hi, thanks for reaching out.

You should create a folder for each of the languages in the setup (I've fixed the broken command in the README), you can copy the files from the downloaded dataset into those folders. The fix for the other issue is simple, add the languages (C, decomC, etc) to the [subtasks list](https://github.com/salesforce/CodeT5/blob/e78a61a17f6dc2f3cbb968447d3e2d065b426e7b/CodeT5/sh/run_exp.py#L134C1-L135C1). I've also updated this in the documentation. 

Let me know if you need anything else 🙂
